### ISSUE TITLE
Uninstall Danger.js

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#493]
## Description
This was never installed 100% correct and we can just point to the contributing docs for PRs that don't follow the guidelines.

We can just uninstall this dependency and remove the config files related to [danger.js](https://danger.systems/js/)

**Comment by KalaRaja** [comment]
@jwu910 I could work on this ticket if you're fine with it.

**Comment by jwu910** [comment]
Go for it, thanks for taking a look!

**Comment by KalaRaja** [comment]
thanks, please assign it to me

**Comment by tanyaleepr** [comment]
Hi. Can I work on this?

**Comment by Jimmy-Vu** [comment]
Hi there, I am currently working on this issue. I am running into an error with `precise-commits` when it runs as part of `husky`'s pre-commit hook. I's running `prettier` on the `.travis.yml` file and throwing a SyntaxError where it expects a random semicolon in the middle of the code.

From what I can tell, it's happening because `prettier` is trying to run the `babel` parser on the `travis.yml`. Just wanted to confirm if it's alright for me to add to the overrides section of the prettier config file to use the `yaml` parser on `.yml` files. YAML support for `prettier` started on [v1.14.0 ](https://prettier.io/blog/2018/07/29/1.14.0.html)and check-it-out's `prettier` is on v1.16.4 so it should be fine.

The proposed change in `.prettierrc` would look like this: 
```yaml
overrides:
  - files: '*.md'
    options:
      parser: markdown
  - files: '{,.}*.{yml,yaml}'
    options:
      parser: yaml
```

**Comment by jwu910** [comment]
hmm, so i _think_ we removed babel, that feels familiar, i would have to double check, I also kinda scrapped travis and we don't quite have CI right now. I think its safe to include just deleting the `.travis.yml` as part of this work as well.

**Comment by Jimmy-Vu** [comment]
From what I see, babel is currently set as the [default parser](https://prettier.io/docs/en/options.html#parser) in `.prettierrc` so I believe it comes with prettier.

This is what `.prettierrc` looks like when I first forked the repo:
```yaml
# .prettierrc
bracketSpacing: true
jsxBracketSameLine: false
parser: babel
printWidth: 80
semi: true
singleQuote: true
trailingComma: all
overrides:
  - files: '*.md'
    options:
      parser: markdown
```

I will delete `.travis.yml` and include the yaml override just in case a future .yml file trips the prettier formatting again. Please let me know if this works for you
